version: '3.9'

services:
  db:
    image: 'postgres:14.4-alpine'
    restart: always
    env_file:
      - ./envs/dev.env
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - ./envs/dev.env
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    